import json

def recursive_stringify(obj):
    """
    Recursively converts any object into a JSON-compatible string.
    Generated by Github Copilot. ❤️

    Args:
        obj: The object to stringify
    """
    def default(o):
        if isinstance(o, (str, int, float, bool)) or o is None:
            return o
        elif isinstance(o, dict):
            return {k: default(v) for k, v in o.items()}
        elif isinstance(o, (list, tuple, set)):
            return [default(item) for item in o]
        elif hasattr(o, "__dict__"):
            return {k: default(v) for k, v in o.__dict__.items()}
        else:
            return str(o)
    return json.dumps(default(obj), ensure_ascii=False)
